# Generated by Django 5.2.4 on 2025-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Lecture Hall', 'Lecture Hall'), ('Library', 'Library'), ('Cafeteria', 'Cafeteria'), ('Office', 'Office'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('map_link', models.URLField(blank=True)),
            ],
        ),
    ]
