# Generated by Django 5.2.4 on 2025-10-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('health', 'Health'), ('finance', 'Finance'), ('registration', 'Registration'), ('clubs', 'Clubs & Societies'), ('ict', 'ICT'), ('other', 'Other')], max_length=20)),
                ('office_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
